apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: springboot-pipeline-java-
build:
  local:
    push: false      # Setting false will not push the image to remote repository
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: sample
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/kubernetes.yml
